### ISSUE TITLE
React 15.2 compatibility

### ISSUE THREAD

**Issue by M3lkior** [martinandert/react-lorem-component#3]
Hi @martinandert 

Since 15.2, React adds warnings when props are not allowed in dom element

Here is warning throws by React for your component : 

```
Warning: Unknown props `count`, `ordered`, `units`, `random` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
```

**Comment by martinandert** [comment]
Hi @M3lkior, thanks for reporting this. It should be fixed in v0.10.1.
